### ISSUE TITLE
How does one access all these apps

### ISSUE THREAD

**Issue by malki2003** [biden2020prez/lgflip-kosher#2]
I installed the yiddish T9, but how do I see it, do I have to go ##228278 every time? Even when I am there I am not able to click on anything.

Also how do I access the Zmanim app, can I add to my main screen instead of th Browser?

**Comment by SZRabinowitz** [comment]
You cannot add it instead of the browser.

In the beginning it prompts you about installing Apps4Flip launcher. Just install it, and open it, and from then on, Apps4Flip launcher will always show in notifications. And from there you can open all your apps.

Let me know if you have any other issues, otherwise I will close this issue. Thanks!
